dataset: "Amazon2M"
seed: 20159
agp:
  - agp_alg: "gdc_agp"
    alpha: 0.2
    rmax: 0.00000001 #1e-8
    L: 20
    ti: 1
  - agp_alg: "gdc_agp"
    alpha: 0.2
    rmax: 0.00000001 #1e-8
    L: 20
    ti: 8
lr: 0.01
dropout: 0.1
hidden: 1024
batch: 100000
weight_decay: 0
layer: 4
bias: 'bn'
epochs: 1000
patience: 100
